apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    compute: db
  name: postgres
  namespace: postgresql-ns
spec:
  nodeName: ip-172-31-44-9      
  containers:
  - image: postgres:10.1
    name: postgres
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "768Mi"
        cpu: "300m"  
    ports:
    - containerPort: 5432  # Exposes container port
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgre-pass
          key: password
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgredb
  volumes:
  - name: postgredb
    persistentVolumeClaim:
      claimName: postgres-pv-claim  
