kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-pv-volume
  labels:
    compute: Application
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
