apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    compute: Application
  name: wordpress
  namespace: wordpress-ns
spec:
  nodeName: ip-172-31-44-75
  containers:
  - image: wordpress:6.2.1-apache
    name: wordpress
    ports:
    - containerPort: 80
      name: wordpress      
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress-postgre
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wordpress-pass
          key: password
    volumeMounts:
    - mountPath: /mnt/data
      name: wordpress-persistent-storage
  volumes:
  - name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: wordpress-pv-claim
