---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    compute: Application
spec:
  selector:
    matchLabels:
      compute: Application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        compute: Application
    spec:
      nodeName: ip-172-31-44-75
      containers:
        - image: wordpress:6.2.1-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-postgres
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: password
            - name: WORDPRESS_DB_USER
              value: wordpress
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim

