kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pv-claim
  labels:
    compute: Application
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
