kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pv-claim  # Sets name of PVC
  namespace: wordpress-ns
  labels:
    compute: Application
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 1Gi  # Sets volume size
