apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-ns
  labels:
    compute: Application
spec:
  ports:
  - port: 80
  selector:
    compute: Application
    tier: frontend
  type: NodePort
